version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: intellisense
      MYSQL_USER: intellisense
      MYSQL_PASSWORD: 123456
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      DB_USERNAME: intellisense
      DB_URL: jdbc:mysql://mysql:3306/intellisense
      MYSQL_DATABASE: intellisense
      MYSQL_PASSWORD: 123456
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  frontend:
    image: giovannagomes/intellisense_front_end:1.0
    restart: always
    environment:
      DB_USERNAME: intellisense
      DB_URL: jdbc:mysql://mysql:3306/intellisense
      API_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - "3333:3333"

volumes:
  mysql_data:
