version: '3.8'

services:
  mysql:
    build:
      context: ./banco-dados
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: intellisense
      MYSQL_USER: intellisense
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      DB_USERNAME: intellisense
      DB_URL: jdbc:mysql://mysql:3306/intellisense
      MYSQL_DATABASE: intellisense
      MYSQL_PASSWORD: 123456
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: intellisense
      DB_URL: jdbc:mysql://mysql:3306/intellisense
      API_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - "3333:3333"

volumes:
  mysql_data:
