# Usar a imagem oficial do MySQL
FROM mysql:8.0

# Variáveis de ambiente para o banco de dados
ENV MYSQL_ROOT_PASSWORD=123456
ENV MYSQL_DATABASE=intellisense
ENV MYSQL_USER=intellisense
ENV MYSQL_PASSWORD=123456

# Expor a porta padrão do MySQL
EXPOSE 3306